version: '3'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
  # database:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
